[package]
name = "link"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
boring = "4.0"
deku = "0.17.0"
duration-str = "0.11.2"
lazy_static = "1.5.0"
paste = "1"
prost = "0.13.1"
quiche = { version = "=0.21.0", features = ["boringssl-boring-crate"] }
ring = "0.17.8"

metrics = { path = "../metrics" }

# workspace
anyhow = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
prost-build = "0.13.1"

[dev-dependencies]
tracing-subscriber = "0"
